# Generated by Django 5.1.5 on 2025-01-31 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'profil', 'verbose_name_plural': 'Profils'},
        ),
    ]
