# Generated by Django 5.1.5 on 2025-01-31 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profil_options'),
        ('pricing', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.product', verbose_name='plan associé'),
        ),
    ]
