# Generated by Django 5.1.5 on 2025-01-31 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profil_plan'),
        ('pricing', '0007_alter_plan_created_at_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.plan', verbose_name='plan associé'),
        ),
    ]
