# Generated by Django 5.1.5 on 2025-01-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profil_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='date de création'),
        ),
    ]
