# Generated by Django 5.1.5 on 2025-01-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profil_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='stripe_customer_id',
            field=models.CharField(max_length=255, null=True, verbose_name='stripe ID'),
        ),
    ]
