# Generated by Django 5.1.5 on 2025-04-19 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_profil_owner"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profil",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="company.company",
                verbose_name="Entreprise associée",
            ),
        ),
        migrations.AddField(
            model_name="profil",
            name="role",
            field=models.CharField(
                choices=[
                    ("regular", "Utilisateur régulier"),
                    ("company_owner", "Propriétaire d'entreprise"),
                ],
                default="regular",
                max_length=20,
                verbose_name="Rôle de l'utilisateur",
            ),
        ),
    ]
