# Generated by Django 5.1.5 on 2025-04-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profil_company_profil_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour'),
        ),
    ]
