# Generated by Django 5.1.5 on 2025-04-26 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profil_last_updated'),
        ('pricing', '0017_alter_subscription_current_period_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.plan', verbose_name='plan associé'),
        ),
    ]
