# Generated by Django 5.1.5 on 2025-04-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_profil_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'profil', 'verbose_name_plural': 'profils'},
        ),
    ]
