# Generated by Django 5.1.5 on 2025-07-13 04:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text="Nom donné à l'appareil par l'utilisateur", max_length=100)),
                ('brand', models.CharField(blank=True, help_text="Marque de l'appareil (Samsung, Apple, etc.)", max_length=50)),
                ('model', models.CharField(blank=True, help_text="Modèle de l'appareil", max_length=100)),
                ('os_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('other', 'Autre')], default='android', max_length=10)),
                ('os_version', models.CharField(blank=True, help_text="Version du système d'exploitation", max_length=20)),
                ('app_version', models.CharField(blank=True, help_text="Version de l'app Antivol", max_length=20)),
                ('imei', models.CharField(blank=True, help_text="IMEI de l'appareil", max_length=20)),
                ('serial_number', models.CharField(blank=True, help_text='Numéro de série', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('lost', 'Perdu'), ('stolen', 'Volé'), ('blocked', 'Bloqué')], default='active', max_length=10)),
                ('is_primary', models.BooleanField(default=False, help_text="Appareil principal de l'utilisateur")),
                ('last_seen', models.DateTimeField(auto_now=True, help_text="Dernière activité de l'appareil")),
                ('unlock_attempts_threshold', models.PositiveIntegerField(default=3, help_text='Nombre de tentatives échouées avant déclenchement')),
                ('photo_capture_enabled', models.BooleanField(default=True, help_text='Capture de photos lors de tentatives échouées')),
                ('location_tracking_enabled', models.BooleanField(default=True, help_text='Suivi de localisation activé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Téléphone',
                'verbose_name_plural': 'Téléphones',
                'ordering': ['-is_primary', '-last_seen'],
                'unique_together': {('user', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='UnlockAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_type', models.CharField(choices=[('pin', 'Code PIN'), ('pattern', 'Schéma'), ('password', 'Mot de passe'), ('fingerprint', 'Empreinte digitale'), ('face', 'Reconnaissance faciale'), ('other', 'Autre')], default='pin', max_length=20)),
                ('result', models.CharField(choices=[('success', 'Réussi'), ('failed', 'Échoué'), ('blocked', 'Bloqué')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('location_accuracy', models.FloatField(blank=True, help_text='Précision en mètres', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_attempts', to='devices.phone')),
            ],
            options={
                'verbose_name': 'Tentative de déverrouillage',
                'verbose_name_plural': 'Tentatives de déverrouillage',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IntrusionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text="Photo prise lors de la tentative d'intrusion", upload_to='intrusion_photos/%Y/%m/%d/')),
                ('camera_type', models.CharField(choices=[('front', 'Frontale'), ('back', 'Arrière')], default='front', max_length=10)),
                ('file_size', models.PositiveIntegerField(help_text='Taille du fichier en octets')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('exif_data', models.JSONField(blank=True, help_text='Données EXIF de la photo', null=True)),
                ('unlock_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='devices.unlockattempt')),
            ],
            options={
                'verbose_name': "Photo d'intrusion",
                'verbose_name_plural': "Photos d'intrusion",
                'ordering': ['-timestamp'],
            },
        ),
    ]
