# Generated by Django 5.1.5 on 2025-07-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='device_id',
            field=models.CharField(help_text="Identifiant unique de l'appareil", max_length=255, unique=True),
        ),
    ]
