# Generated by Django 5.1.5 on 2025-01-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='date de commande')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom du plan')),
                ('storage', models.FloatField(verbose_name='espace de stockage')),
                ('monthly_amount', models.FloatField(verbose_name='montant par mois (€)')),
                ('yearly_amount', models.FloatField(verbose_name='montant par an (€)')),
                ('type', models.CharField(choices=[('free', 'Gratuit'), ('standard', 'Standard'), ('custom', 'Personnalisé')], default='standard', max_length=10, verbose_name='Type')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
