# Generated by Django 5.1.5 on 2025-01-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='storage',
            field=models.FloatField(verbose_name='espace de stockage (Go)'),
        ),
    ]
