# Generated by Django 5.1.5 on 2025-01-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_plan_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='date de commande')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom du produit')),
                ('description', models.TextField(max_length=500, verbose_name='description du produit')),
                ('storage', models.FloatField(verbose_name='espace de stockage (Go)')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
                ('monthly_amount', models.FloatField(verbose_name='montant par mois (€)')),
                ('yearly_amount', models.FloatField(verbose_name='montant par an (€)')),
                ('type', models.CharField(choices=[('free', 'Gratuit'), ('standard', 'Standard'), ('custom', 'Personnalisé')], default='standard', max_length=10, verbose_name='Type')),
                ('stripe_product_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='stripe ID')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['-created_at'],
            },
        ),
    ]
