# Generated by Django 5.1.5 on 2025-01-31 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profil_plan'),
        ('pricing', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
