# Generated by Django 5.1.5 on 2025-01-31 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_delete_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='product',
            name='monthly_amount',
            field=models.FloatField(verbose_name='montant/mois (€)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.FloatField(verbose_name='stockage (Go)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='yearly_amount',
            field=models.FloatField(verbose_name='montant/an (€)'),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
                ('amount', models.IntegerField(verbose_name='montant')),
                ('created', models.DateTimeField(verbose_name='date de création')),
                ('currency', models.CharField(default='EUR', max_length=10, verbose_name='devise')),
                ('interval', models.CharField(max_length=10, verbose_name='intervalle')),
                ('interval_count', models.IntegerField(default=1, verbose_name="nombre d'intervalle")),
                ('trial_period_days', models.IntegerField(blank=True, null=True, verbose_name="jours de période d'essai")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='pricing.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['-created'],
            },
        ),
    ]
