# Generated by Django 5.1.5 on 2025-01-31 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-created_at'], 'verbose_name': 'plan', 'verbose_name_plural': 'plans'},
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='monthly_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='yearly_amount',
        ),
    ]
