# Generated by Django 5.1.5 on 2025-01-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_alter_plan_options_rename_created_plan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='description du produit'),
        ),
    ]
