# Generated by Django 5.1.5 on 2025-01-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_alter_plan_created_at_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_plan_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='stripe ID'),
        ),
    ]
