# Generated by Django 5.1.5 on 2025-01-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_plan_stripe_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='EUR', max_length=4, verbose_name='devise'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='interval',
            field=models.CharField(choices=[('day', 'Jour'), ('week', 'Semaine'), ('month', 'Mois'), ('year', 'Année')], default='month', max_length=10, verbose_name='intervalle'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='trial_period_days',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="période d'essai(jours)"),
        ),
    ]
