# Generated by Django 5.1.5 on 2025-01-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(null=True, verbose_name='fin de la période actuelle'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateTimeField(null=True, verbose_name='début de la période actuelle'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('canceled', 'Annulé'), ('expired', 'Expiré')], default='active', max_length=10, null=True, verbose_name='statut'),
        ),
    ]
