# Generated by Django 5.1.5 on 2025-01-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0012_subscription_current_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_session_id',
            field=models.CharField(max_length=255, null=True, verbose_name='ID de la session Stripe'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactif'), ('active', 'Actif'), ('canceled', 'Annulé'), ('expired', 'Expiré')], default='inactive', max_length=10, null=True, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(max_length=255, null=True, verbose_name='ID de la souscription Stripe'),
        ),
    ]
