# Generated by Django 5.1.5 on 2025-02-03 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_subscription_stripe_session_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='montant dû'),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='montant payé'),
        ),
        migrations.AddField(
            model_name='payment',
            name='billing_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='raison de facturation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de création stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email du client'),
        ),
        migrations.AddField(
            model_name='payment',
            name='hosted_invoice_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la facture hébergée'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_pdf',
            field=models.URLField(blank=True, null=True, verbose_name='PDF de la facture'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='payé'),
        ),
        migrations.AddField(
            model_name='payment',
            name='period_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fin de période'),
        ),
        migrations.AddField(
            model_name='payment',
            name='period_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='début de période'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de la facture Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant (€)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(max_length=10, verbose_name='devise'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(null=True, verbose_name='fin de période'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateTimeField(null=True, verbose_name='début de période'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='pricing.plan', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactif'), ('active', 'Actif'), ('canceled', 'Annulé'), ('expired', 'Expiré')], default='inactive', editable=False, max_length=10, null=True, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
    ]
