# Generated by Django 5.1.5 on 2025-02-15 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0014_payment_amount_due_payment_amount_paid_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='payment',
        #     name='plan',
        # ),
        # migrations.RemoveField(
        #     model_name='payment',
        #     name='user',
        # ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pricing.subscription', verbose_name='Souscription'),
        ),
    ]
