# Generated by Django 5.1.5 on 2025-02-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0015_remove_payment_plan_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
