# Generated by Django 5.1.5 on 2025-04-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0016_remove_payment_plan_remove_payment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="current_period_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="fin de période"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="current_period_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="début de période"
            ),
        ),
    ]
