# Generated by Django 5.1.5 on 2025-04-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0017_alter_subscription_current_period_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[
                    ("free", "Gratuit"),
                    ("standard", "Standard"),
                    ("custom", "Personnalisé"),
                    ("company_catalog", "Catalogue Entreprise"),
                ],
                default="standard",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
