# Generated by Django 5.1.5 on 2025-04-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0018_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de la session Stripe'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de la souscription Stripe'),
        ),
    ]
