# Generated by Django 5.1.5 on 2025-01-25 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_alter_box_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ['-created_at'], 'verbose_name': 'Box', 'verbose_name_plural': 'Boxes'},
        ),
        migrations.AlterField(
            model_name='box',
            name='mac_address',
            field=models.CharField(max_length=100, unique=True, verbose_name='adresse mac'),
        ),
        migrations.AlterField(
            model_name='box',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propriétaire', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
    ]
