# Generated by Django 5.1.5 on 2025-02-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_alter_box_options_alter_box_mac_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='socket_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de socket'),
        ),
    ]
