# Generated by Django 5.1.5 on 2025-02-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0004_box_socket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='is_connected',
            field=models.BooleanField(default=False, verbose_name='est connecté'),
        ),
    ]
