# Generated by Django 5.1.5 on 2025-02-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0005_box_is_connected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ['-created_at'], 'verbose_name': 'box', 'verbose_name_plural': 'boxes'},
        ),
        migrations.AlterField(
            model_name='box',
            name='is_connected',
            field=models.BooleanField(default=False, verbose_name='connecté ?'),
        ),
        migrations.AlterField(
            model_name='box',
            name='socket_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='socket ID'),
        ),
    ]
