# Generated by Django 5.1.5 on 2025-07-18 01:59

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_add_verification_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="verification_code",
            field=models.CharField(
                default=authentication.models.generate_verification_code, max_length=6
            ),
        ),
    ]
