# Generated by Django 5.1.5 on 2025-01-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_sharedalbum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
    ]
