# Generated by Django 5.1.5 on 2025-01-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_album_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created_at'], 'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.AlterModelOptions(
            name='sharedalbum',
            options={'ordering': ['-created_at'], 'verbose_name': 'album partagé', 'verbose_name_plural': 'albums partagés'},
        ),
    ]
