# Generated by Django 5.1.5 on 2025-01-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_alter_photo_options_alter_sharedalbum_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='albums', to='album.photo', verbose_name='photos'),
        ),
        migrations.AddField(
            model_name='album',
            name='shared_with_sharing',
            field=models.ManyToManyField(blank=True, related_name='shared_albums', to='album.sharedalbum', verbose_name='albums partagés'),
        ),
    ]
