# Generated by Django 5.1.5 on 2025-01-29 17:39

import album.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_album_photos_album_shared_with_sharing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='album',
            name='shared_with_sharing',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(upload_to=album.models.user_directory_path, verbose_name='image'),
        ),
    ]
