# Generated by Django 5.1.5 on 2025-02-05 17:45

import album.models
import django_clamd.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_remove_album_photos_remove_album_shared_with_sharing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to=album.models.user_directory_path, validators=[django_clamd.validators.validate_file_infection], verbose_name='image'),
        ),
    ]
