# Generated by Django 5.1.5 on 2025-02-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0008_alter_album_id_alter_photo_id_alter_sharedalbum_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-created_at'], 'verbose_name': 'album', 'verbose_name_plural': 'albums'},
        ),
        migrations.AddField(
            model_name='sharedalbum',
            name='status',
            field=models.CharField(choices=[('pending', 'Gratuit'), ('accepted', 'Accepté'), ('denied', 'Refusé'), ('expiry', 'Expiré')], default='pending', max_length=10, verbose_name='statut'),
        ),
    ]
