# Generated by Django 5.1.5 on 2025-02-15 15:04

import album.models
import django.core.validators
import django_clamd.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0009_alter_album_options_sharedalbum_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to=album.models.user_directory_path, validators=[django_clamd.validators.validate_file_infection, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp'])], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='sharedalbum',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('denied', 'Refusé'), ('expiry', 'Expiré')], default='pending', max_length=10, verbose_name='statut'),
        ),
    ]
