# Generated by Django 5.1.5 on 2025-04-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="location",
        ),
        migrations.AddField(
            model_name="company",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude"),
        ),
        migrations.AddField(
            model_name="company",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="nom"),
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(max_length=255, verbose_name="adresse"),
        ),
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.CharField(max_length=100, verbose_name="ville"),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=255, verbose_name="nom"),
        ),
        migrations.AlterField(
            model_name="company",
            name="postal_code",
            field=models.CharField(max_length=10, verbose_name="code postal"),
        ),
    ]
