# Generated by Django 5.1.5 on 2025-04-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='closing_hour',
            field=models.TimeField(blank=True, default='16:00', null=True, verbose_name='Heure de fermeture'),
        ),
        migrations.AddField(
            model_name='company',
            name='opening_hour',
            field=models.TimeField(blank=True, default='08:00', null=True, verbose_name="Heure d'ouverture"),
        ),
    ]
