# Generated by Django 5.1.5 on 2025-04-27 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_closing_hour_company_opening_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la ville')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_zones', to='company.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Zone de diffusion',
                'verbose_name_plural': 'Zones de diffusion',
                'ordering': ['name'],
                'unique_together': {('name', 'company')},
            },
        ),
        migrations.AddField(
            model_name='catalog',
            name='distribution_zones',
            field=models.ManyToManyField(related_name='catalogs', to='company.distributionzone', verbose_name='Zones de diffusion'),
        ),
    ]
