# Generated by Django 5.1.5 on 2025-04-27 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_distributionzone_catalog_distribution_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 0, 11, 24, 842631), verbose_name='Date de création'),
        ),
    ]
