# Generated by Django 5.1.5 on 2025-04-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_alter_company_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("city_hall", "Mairie"),
                            ("pharmacy", "Pharmacie de garde"),
                        ],
                        max_length=20,
                        verbose_name="Type de service",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Adresse")),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Code postal"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Site web"),
                ),
                ("latitude", models.FloatField(verbose_name="Latitude")),
                ("longitude", models.FloatField(verbose_name="Longitude")),
                (
                    "opening_hour",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure d'ouverture"
                    ),
                ),
                (
                    "closing_hour",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de fermeture"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Service public",
                "verbose_name_plural": "Services publics",
                "ordering": ["service_type", "city", "name"],
                "unique_together": {("service_type", "name", "city")},
            },
        ),
    ]
