# Generated by Django 5.1.5 on 2025-04-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_publicservice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicservice",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ville"),
        ),
        migrations.AlterField(
            model_name="publicservice",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="publicservice",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude"),
        ),
        migrations.AlterField(
            model_name="publicservice",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Code postal"
            ),
        ),
    ]
