# Generated by Django 5.1.5 on 2025-04-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0009_alter_publicservice_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicservice",
            name="closing_hour",
            field=models.TimeField(
                default="09:00:00", verbose_name="Heure de fermeture"
            ),
        ),
        migrations.AlterField(
            model_name="publicservice",
            name="opening_hour",
            field=models.TimeField(
                default="19:00:00", verbose_name="Heure d'ouverture"
            ),
        ),
    ]
