# Generated by Django 5.1.5 on 2025-04-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_alter_publicservice_closing_hour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicservice",
            name="service_type",
            field=models.CharField(
                choices=[("city_hall", "Mairie"), ("pharmacy", "Pharmacie de garde")],
                default="city_hall",
                max_length=20,
                verbose_name="Type de service",
            ),
        ),
    ]
