# Generated by Django 5.1.5 on 2025-04-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0011_alter_publicservice_service_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicservice",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ville"
            ),
        ),
    ]
