# Generated by Django 5.1.5 on 2025-04-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0013_alter_publicservice_closing_hour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicservice",
            name="phone",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Téléphone"
            ),
        ),
    ]
