# Generated by Django 5.1.5 on 2025-05-02 00:05

import company.models
import django.core.validators
import django_clamd.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_publicservice_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Entreprise active'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Entreprise bannie'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='file',
            field=models.FileField(upload_to=company.models.catalog_file_path, validators=[django_clamd.validators.validate_file_infection, django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Fichier PDF'),
        ),
    ]
